<a href="https://colab.research.google.com/github/lilianabs/learning-pytorch/blob/main/Tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import torch
import numpy as np

In [34]:
# Scalar value
x = torch.empty(1)
x

tensor([2.1715e-18])

In [35]:
# 1D array with 3 elements
x = torch.empty(3)
x

tensor([-9.4989e+37,  4.5849e-41,  7.3548e-38])

In [36]:
x = torch.empty(2, 3)
x

tensor([[ 2.8728e-35,  0.0000e+00, -9.4988e+37],
        [ 4.5849e-41,  8.9683e-44,  0.0000e+00]])

In [37]:
x = torch.empty(2, 2, 3)
x

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])

In [38]:
# 2x2 tensor with random elements
x = torch.rand(2, 2)
x

tensor([[0.2896, 0.1838],
        [0.4159, 0.2099]])

In [39]:
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

In [40]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [41]:
print(x.dtype)

torch.float32


In [42]:
x = torch.ones(2, 2, dtype=torch.double)
print(x, x.dtype)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) torch.float64


In [43]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x, x.dtype)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16) torch.float16


In [44]:
print(x.size())

torch.Size([2, 2])


In [45]:
# Build a tensor from a python list
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

## Tensor operations

In [46]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

tensor([[0.4654, 0.2975],
        [0.7413, 0.9478]])
tensor([[0.7436, 0.3030],
        [0.5060, 0.2081]])


In [47]:
z = x + y
z

tensor([[1.2090, 0.6005],
        [1.2473, 1.1559]])

In [48]:
z = torch.add(x, y)
z

tensor([[1.2090, 0.6005],
        [1.2473, 1.1559]])

In [49]:
# inplace addition
y.add_(x)
y

tensor([[1.2090, 0.6005],
        [1.2473, 1.1559]])

## Slicing

In [50]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])

tensor([[0.2608, 0.0724, 0.9219],
        [0.8475, 0.7733, 0.7185],
        [0.3823, 0.9266, 0.3044],
        [0.8825, 0.8855, 0.2363],
        [0.4318, 0.9427, 0.4925]])
tensor([0.2608, 0.8475, 0.3823, 0.8825, 0.4318])


In [51]:
print(x[1, 1])

tensor(0.7733)


In [52]:
# Get the actual value
print(x[1, 1].item())

0.7732517123222351


## Reshaping a tensor

In [53]:
x = torch.rand(4, 4)
x

tensor([[0.8066, 0.1795, 0.6771, 0.8192],
        [0.4890, 0.6061, 0.3030, 0.0705],
        [0.2020, 0.0679, 0.5882, 0.2462],
        [0.0568, 0.4139, 0.5114, 0.4018]])

In [54]:
y = x.view(16)
y

tensor([0.8066, 0.1795, 0.6771, 0.8192, 0.4890, 0.6061, 0.3030, 0.0705, 0.2020,
        0.0679, 0.5882, 0.2462, 0.0568, 0.4139, 0.5114, 0.4018])

In [55]:
y = x.view(-1, 8)
y

tensor([[0.8066, 0.1795, 0.6771, 0.8192, 0.4890, 0.6061, 0.3030, 0.0705],
        [0.2020, 0.0679, 0.5882, 0.2462, 0.0568, 0.4139, 0.5114, 0.4018]])

In [56]:
y.size()

torch.Size([2, 8])

## Converting to numpy array

In [57]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [58]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [59]:
print(type(b))

<class 'numpy.ndarray'>


In [60]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [61]:
print(b)

[2. 2. 2. 2. 2.]


In [62]:
a = np.ones(5, dtype=np.float16)
print(a)

[1. 1. 1. 1. 1.]


In [63]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float16)

## Checking for cuda

In [64]:
if torch.cuda.is_available():
  print("Device found")

Device found


In [65]:
device = torch.device("cuda")

In [66]:
x = torch.ones(5, device=device)
x

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [68]:
y = torch.ones(5)
y = y.to(device)

In [69]:
z = x + y
z

tensor([2., 2., 2., 2., 2.], device='cuda:0')

In [70]:
# z.numpy() returns error because numpy can only handle cpu

In [71]:
z = z.to("cpu")
z.numpy()

array([2., 2., 2., 2., 2.], dtype=float32)

In [73]:
# Tell pytorch we require it to calculate gradients for the tensor
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)